spring:
  datasource:
    url: 'jdbc:h2:mem:library'
    username: 'user'
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: '/h2-console'

#  profiles:
#    active: chaos-monkey
chaos:
  monkey:
    enabled: true
    watcher:
      service: true
      repository: true
    assaults:
      latencyActive: true

management:
endpoint:
  chaosmonkey:
    enabled: true
  chaosmonkeyjmx:
    enabled: true

endpoints:
  web:
    exposure:
      # include all endpoints
#      include: "*"
      # include specific endpoints
      include:
        - health
        - info
        - chaosmonkey